### ISSUE TITLE
Build error: Could not find com.google.android:flexbox:2.0.1.

### ISSUE THREAD

**Issue by MarkusPorti** [Dhaval2404/ColorPicker#21]
## Summary

When I try to build my project, theres this error:
```
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.google.android:flexbox:2.0.1.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/google/android/flexbox/2.0.1/flexbox-2.0.1.pom
       - https://repo.maven.apache.org/maven2/com/google/android/flexbox/2.0.1/flexbox-2.0.1.pom
       - https://jitpack.io/com/google/android/flexbox/2.0.1/flexbox-2.0.1.pom
     Required by:
         project :app > com.github.Dhaval2404:ColorPicker:v2.0

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
```
I think it's because I don't use the repository "jcenter()" anymore (it's deprecated).

In https://stackoverflow.com/questions/53709146/failed-to-resolve-com-google-androidflexbox1-1-0 theres a similar problem.
They fixed it by using the dependency
`com.google.android.flexbox:flexbox:3.0.0`
instead of
`com.google.android:flexbox:2.0.1`

It would be nice if this project could also use mavenCentral() instead of jcenter() and try to Update this

@Dhaval2404 do you think you could test this?

**Comment by jamaghafoor** [comment]
Thanks. It helped me out.
