### ISSUE TITLE
How to choose Grey / Black colors

### ISSUE THREAD

**Issue by Javierenrique00** [Dhaval2404/ColorPicker#6]
Hello,
I´m using ColorPicker, but I don't find how with ColorPicker Dialog choose dark colors like grey or Black. Are there any parameters to set this tones ?

**Comment by Dhaval2404** [comment]
@Javierenrique00 You can specify the custom color in Builder Class

![image](https://user-images.githubusercontent.com/7314181/79542952-37f7be00-80aa-11ea-8c79-1539d99c4cd5.png)

Please check the [Customization ](https://github.com/Dhaval2404/ColorPicker#customization) section of README.
