### ISSUE TITLE
MinSdkVersion dk 21?

### ISSUE THREAD

**Issue by Naguchennai** [Dhaval2404/ColorPicker#9]
MinSdkVersion dk 21? sorry we cant use it .. what about all other 50% users?

**Comment by marcauberer** [comment]
API level 21 is the current recommended target API version from Google with >90%. You should consider to upgrade your app to target API level 21. Sorry for the sobering answer.

**Comment by Dhaval2404** [comment]
@MonkeyMok As per the latest Android API Distribution, This library cover 94% of devices. So, for now, I will stick to API 21.

![image](https://user-images.githubusercontent.com/7314181/102356220-f15cb980-3fd2-11eb-9d1e-834bfe248d2b.png)

Thank you!
